#!/usr/bin/env php
<?php
set_time_limit(0);
require_once(dirname(__FILE__) . '/../bootstrap.php');

$doorbell = new Doorbell((int)$GLOBALS['config']['gpio']['pin'], $app->db);
$doorbell->saveWebcam();
